%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Second-year\Code\giuseppe\gene_ids.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2021/02/17 12:50:25

%% Initialize variables.
filename = 'D:\Second-year\Code\giuseppe\gene_ids.csv';
delimiter = {'\n'};

%% Format for each line of text:
%   column1: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
geneids = double(dataArray{1:end-1}, 'VariableNames', {'bcr_patient_barcode'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;